global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - follow_redirects: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets:
            - alertmanager:9093
rule_files:
  - /etc/prometheus/alerts/alert.rules
scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9090
  - job_name: lava-provider
    metrics_path: /metrics
    static_configs:
      - targets:
          - PROVIDER_IP:PROVIDER_PORT  # for example 1.2.3.4:14447
        labels:
          instance: mainnet
  - job_name: lava-provider-cache
    metrics_path: /metrics
    static_configs:
      - targets:
          - PROVIDER_IP:CACHE_PORT  # for example 1.2.3.4:7780
        labels:
          instance: mainnet
