{
 "title": "Lava Provider Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "environment", "label": "environment", "query": "testnet, mainnet" }
  ]
 },
 "panels": [
  {
   "title": "CU Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(spec) (lava_provider_total_relays_serviced{job=\"provider-$environment\"})",
     "legendFormat": "{{spec}}"
    },
    {
     "expr": "sum by(spec) (lava_provider_total_cu_serviced{job=\"provider-$environment\"})",
     "legendFormat": "{{spec}}"
    },
    {
     "expr": "sum by(spec) (lava_provider_total_cu_paid{job=\"provider-$environment\"})",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  { "title": "Provider Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Block Update Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(spec) (sum by(spec) (rate(lava_provider_last_serviced_block_update_time_seconds{job=\"provider-$environment\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provider Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lava_provider_frozen_status{job=\"provider-$environment\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lava_latest_block{job=\"provider-$environment\",spec!~\"lava\"}",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "Errors in last 24h",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(spec) (increase(lava_provider_total_errored{job=\"provider-$environment\"}[24h]))",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "QoS Availability",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(spec) (lava_consumer_QoS{qos_metric=\"availability\", job=\"provider-$environment\"})",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "QoS Latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(spec) (lava_consumer_QoS{qos_metric=\"latency\", job=\"provider-$environment\"})",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "QoS Sync",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(spec) (lava_consumer_QoS{qos_metric=\"sync/freshness\", job=\"provider-$environment\"})",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "QoS Availability",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(spec) (lava_consumer_QoS{qos_metric=\"availability\", job=\"provider-$environment\"})*100",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "QoS Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(spec) (lava_consumer_QoS{qos_metric=\"latency\", job=\"provider-$environment\"})*100",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "QoS Sync",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(spec) (lava_consumer_QoS{qos_metric=\"sync/freshness\", job=\"provider-$environment\"})*100",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "Total requests by API [24h]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(apiInterface) (increase(lava_provider_total_cu_serviced{job=\"provider-$environment\"}[24h]))",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  {
   "title": "Total requests by SPEC [24h]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(spec) (increase(lava_provider_total_cu_serviced{job=\"provider-$environment\"}[24h]))",
     "legendFormat": "{{apiInterface}}"
    }
   ]
  },
  {
   "title": "Errors in Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "expr": "sum(lava_provider_total_errored{job=\"provider-$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Active nodes rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Requests rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(apiInterface,spec) (rate(lava_provider_total_cu_serviced{job=\"provider-$environment\"}[10m]))",
     "legendFormat": "{{spec}}-{{apiInterface}}"
    }
   ]
  },
  {
   "title": "Requests peak rate",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(spec) (rate(lava_provider_total_cu_serviced{job=\"provider-$environment\"}[1m]))",
     "legendFormat": "{{spec}}"
    }
   ]
  },
  {
   "title": "Cache: Requests rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(chain_id,result) (rate(cache_api_specifics{job=\"provider-$environment\"}[10m]))",
     "legendFormat": "{{chain_id}}-{{result}}"
    }
   ]
  },
  {
   "title": "Requests peak rate",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(chain_id) (rate(cache_api_specifics{job=\"provider-$environment\"}[1m]))",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  {
   "title": "Cache: Total number of hits",
   "type": "stat",
   "description": "The total number of hits the cache server managed to reply",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cache_total_hits{job=\"provider-$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache: Total number of hits rate",
   "type": "timeseries",
   "description": "The total number of hits the cache server managed to reply",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(cache_total_hits{job=\"provider-$environment\"}[1m])",
     "legendFormat": "hits"
    }
   ]
  },
  {
   "title": "Cache: Total number of misses",
   "type": "stat",
   "description": "The total number of misses the cache server could not reply.",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cache_total_misses{job=\"provider-$environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache: Total number of misses rate",
   "type": "timeseries",
   "description": "The total number of misses the cache server could not reply.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(cache_total_misses{job=\"provider-$environment\"}[10m])",
     "legendFormat": "misses"
    }
   ]
  }
 ]
}